"""Sync mutation status to MUTATIONS_ROADMAP.md and push to GitHub.

This ensures the roadmap is centrally available regardless of which
daemon instance is running or where it's hosted. All daemons push
to the same git repo, making the roadmap the shared source of truth.

Called from evolution.py _save_mutation() after every status change.
"""

import os
import subprocess
from datetime import datetime
from pathlib import Path
from typing import Dict, Any

PROJECT_ROOT = Path(__file__).resolve().parent.parent
ROADMAP_FILE = PROJECT_ROOT / "MUTATIONS_ROADMAP.md"

PILLAR_NAMES = {
    1: "Self-Evolution",
    2: "Resource Optimization",
    3: "Model Agnosticism",
    4: "Durable State",
    5: "Companion Alignment",
}

STATUS_ICONS = {
    "proposed": "🟡",
    "pending_approval": "🟡",
    "approved": "🔵",
    "implemented": "🟢",
    "promoted": "🟢",
    "rejected": "🔴",
    "rolled_back": "🔴",
    "failed": "🔴",
}

# Only sync these statuses to avoid noise from every proposed mutation
SYNC_STATUSES = {"approved", "implemented", "promoted", "rejected", "rolled_back", "failed"}


def sync_to_roadmap(mutation: Dict[str, Any], push: bool = True) -> None:
    """
    Update MUTATIONS_ROADMAP.md with mutation status and push to GitHub.
    
    Args:
        mutation: Mutation dict (or object with to_dict())
        push: Whether to git commit and push (default True for central storage)
    """
    try:
        # Normalize mutation to dict
        if hasattr(mutation, "to_dict"):
            mutation = mutation.to_dict()

        status = mutation.get("status", "proposed")
        if hasattr(status, "value"):
            status = status.value

        # Only sync significant status changes to avoid noise
        if status not in SYNC_STATUSES:
            return

        mutation_id = str(mutation.get("mutation_id", "unknown"))[:12]
        description = str(mutation.get("description", "No description"))[:80]
        pillar = mutation.get("mission_pillar")
        pillar_name = PILLAR_NAMES.get(pillar, "Unknown") if pillar else "Unknown"
        icon = STATUS_ICONS.get(status, "⚪")
        date = datetime.utcnow().strftime("%Y-%m-%d %H:%M")
        agent = mutation.get("agent_name", "unknown")

        entry = f"| {icon} {status} | `{mutation_id}` | {pillar_name} | {description} | {agent} | {date} |"

        # Read existing roadmap
        lines = []
        if ROADMAP_FILE.exists():
            lines = ROADMAP_FILE.read_text().splitlines(keepends=True)

        # Find or create the table
        header_idx = -1
        for i, line in enumerate(lines):
            if line.startswith("| Status"):
                header_idx = i
                break

        if header_idx == -1:
            lines = [
                "# Mutations Roadmap\n",
                "\n",
                "Auto-generated by the council. Tracks mutation outcomes across all daemon instances.\n",
                "This file is the central source of truth — pushed to GitHub after every significant status change.\n",
                "\n",
                "| Status | ID | Pillar | Description | Agent | Date |\n",
                "|--------|-----|--------|-------------|-------|------|\n",
            ]
            header_idx = 5

        # Check if mutation already exists (update in place)
        existing_idx = -1
        for i, line in enumerate(lines):
            if mutation_id in line:
                existing_idx = i
                break

        if existing_idx >= 0:
            lines[existing_idx] = entry + "\n"
        else:
            # Insert after header separator
            insert_at = header_idx + 2
            lines.insert(insert_at, entry + "\n")

        # Keep only last 200 entries
        table_start = header_idx + 2
        table_lines = [l for l in lines[table_start:] if l.startswith("|")]
        if len(table_lines) > 200:
            lines = lines[:table_start] + table_lines[:200]

        ROADMAP_FILE.write_text("".join(lines))

        # Push to GitHub (central storage)
        if push:
            _git_push_roadmap(mutation_id, status)

    except Exception as e:
        print(f"[ROADMAP] Failed to sync: {e}")


def _git_push_roadmap(mutation_id: str, status: str) -> None:
    """Commit and push MUTATIONS_ROADMAP.md to origin."""
    try:
        subprocess.run(
            ["git", "add", "MUTATIONS_ROADMAP.md"],
            cwd=str(PROJECT_ROOT),
            capture_output=True,
            timeout=10,
        )
        subprocess.run(
            ["git", "commit", "-m", f"roadmap: {mutation_id} → {status}"],
            cwd=str(PROJECT_ROOT),
            capture_output=True,
            timeout=10,
        )
        subprocess.run(
            ["git", "push", "origin", "main"],
            cwd=str(PROJECT_ROOT),
            capture_output=True,
            timeout=15,
        )
    except Exception as e:
        print(f"[ROADMAP] Git push failed: {e}")


def get_roadmap_entries() -> list:
    """Read all roadmap entries (for dedup checking by council)."""
    entries = []
    try:
        if ROADMAP_FILE.exists():
            for line in ROADMAP_FILE.read_text().splitlines():
                if line.startswith("|") and "`" in line:
                    entries.append(line)
    except Exception:
        pass
    return entries


def is_already_tracked(description: str) -> bool:
    """Check if a similar mutation is already in the roadmap."""
    try:
        entries = get_roadmap_entries()
        desc_lower = description.lower()[:40]
        for entry in entries:
            if desc_lower in entry.lower():
                return True
    except Exception:
        pass
    return False
