"""
Mutation Rollback Analyzer

Analyzes failed mutation rollbacks, extracts root causes, and logs patterns
into core/learning.py to guide future mutation proposals.
"""

import json
import os
from datetime import datetime

ROLLBACK_LOG_PATH = "rollback_log.json"
LEARNING_MODULE_PATH = "core/learning.py"


def load_rollback_log():
    if not os.path.exists(ROLLBACK_LOG_PATH):
        return []
    with open(ROLLBACK_LOG_PATH, "r") as f:
        return json.load(f)


def extract_patterns(rollback_entries):
    patterns = []
    for entry in rollback_entries:
        reason = entry.get("reason", "")
        mutation_type = entry.get("mutation_type", "")
        if "test failed" in reason.lower():
            patterns.append({
                "pattern": "test_failure",
                "mutation_type": mutation_type,
                "detail": reason,
                "timestamp": entry.get("timestamp", datetime.utcnow().isoformat())
            })
        elif "dependency" in reason.lower():
            patterns.append({
                "pattern": "dependency_issue",
                "mutation_type": mutation_type,
                "detail": reason,
                "timestamp": entry.get("timestamp", datetime.utcnow().isoformat())
            })
        elif "import" in reason.lower():
            patterns.append({
                "pattern": "import_error",
                "mutation_type": mutation_type,
                "detail": reason,
                "timestamp": entry.get("timestamp", datetime.utcnow().isoformat())
            })
    return patterns


def feed_to_learning(patterns):
    """Append patterns to core/learning.py as a structured list."""
    if not patterns:
        return
    # Read existing learning module
    with open(LEARNING_MODULE_PATH, "r") as f:
        content = f.read()
    # Append pattern data as a comment block for future parsing
    pattern_block = "\n# Rollback patterns (auto-generated by mutation_rollback_analyzer)\n"
    pattern_block += "ROLLBACK_PATTERNS = " + json.dumps(patterns, indent=2) + "\n"
    with open(LEARNING_MODULE_PATH, "a") as f:
        f.write(pattern_block)


def analyze():
    log = load_rollback_log()
    patterns = extract_patterns(log)
    feed_to_learning(patterns)
    return {"analyzed": len(log), "patterns_found": len(patterns)}


if __name__ == "__main__":
    result = analyze()
    print(json.dumps(result))
