"""
test_component - Autonomous Council Microservice
Platform: replit
Generated by Phase B Deployment Packager
"""
import os
import sys
import json
import uuid
import asyncio
import logging
from pathlib import Path
from datetime import datetime
from typing import Dict, Any, Optional

# Add project root to path for imports
project_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(project_root))

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import httpx

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("test_component")

# Configuration
NODE_ID = os.getenv("NODE_ID", f"test_component-{uuid.uuid4().hex[:8]}")
COUNCIL_URL = os.getenv("COUNCIL_URL", "http://localhost:8000")
SHARED_SECRET = os.getenv("SHARED_SECRET", "")
PORT = int(os.getenv("PORT", "8000"))

app = FastAPI(title="test_component", version="1.0.0")

# Task models
class TaskRequest(BaseModel):
    task_id: str
    input: Dict[str, Any]
    callback_url: Optional[str] = None

class TaskResult(BaseModel):
    task_id: str
    node_id: str
    status: str
    result: Dict[str, Any]
    timestamp: str


# Import the actual component logic
try:
    from core.test import component as _component_func
    logger.info(f"Loaded component: {spec.entry_point}")
except Exception as e:
    logger.error(f"Failed to load component {spec.entry_point}: {e}")
    _component_func = None


@app.get("/health")
async def health():
    """Health check endpoint."""
    return {
        "node_id": NODE_ID,
        "component": "test_component",
        "platform": "replit",
        "status": "healthy",
        "uptime_seconds": 0,
        "timestamp": datetime.utcnow().isoformat()
    }


@app.post("/task")
async def handle_task(request: TaskRequest):
    """Execute a task and optionally report result back to council."""
    if _component_func is None:
        raise HTTPException(status_code=500, detail="Component not loaded")
    
    logger.info(f"Executing task {request.task_id}")
    
    try:
        # Execute the component function
        if asyncio.iscoroutinefunction(_component_func):
            result = await _component_func(request.input)
        else:
            result = _component_func(request.input)
        
        response = TaskResult(
            task_id=request.task_id,
            node_id=NODE_ID,
            status="completed",
            result={"output": result},
            timestamp=datetime.utcnow().isoformat()
        )
        
        # Report back to council if callback provided
        if request.callback_url:
            await _report_result(request.callback_url, response)
        
        return response
        
    except Exception as e:
        logger.error(f"Task {request.task_id} failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))


async def _report_result(callback_url: str, result: TaskResult):
    """Report task result back to council."""
    try:
        async with httpx.AsyncClient(timeout=30) as client:
            response = await client.post(
                callback_url,
                json=result.dict(),
                headers={"Content-Type": "application/json"}
            )
            response.raise_for_status()
    except Exception as e:
        logger.error(f"Failed to report result: {e}")


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=PORT)
